config/routes.rb
CmsTerms::Application.routes.draw do

  resources :user_page_checks do
      member do
        delete 'check'
      end
  end

  resources :notes
  devise_for :users
  resources :pages do
      member do
        get 'view'
      end
  end

  

  root :to => "homes#index"
end

app/models/user_page_check.rb
class UserPageCheck < ActiveRecord::Base
  attr_accessible :user_id, :page_id


  belongs_to :page, :class_name => 'Page', :foreign_key => 'page_id'
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
end

app/controllers/user_page_checks_controller.rb
class UserPageChecksController < ApplicationController
  
  before_action :set_user_page_check, only: [:show, :edit, :update, :destroy, :check]


  def check
    @user_page_check.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  # GET /user_page_checks
  # GET /user_page_checks.json
  def index
    @user_page_checks = UserPageCheck.all
  end

  # GET /user_page_checks/1
  # GET /user_page_checks/1.json
  def show
  end

  # GET /user_page_checks/new
  def new
    @user_page_check = UserPageCheck.new
  end

  # GET /user_page_checks/1/edit
  def edit
  end

  # POST /user_page_checks
  # POST /user_page_checks.json
  def create
    @user_page_check = UserPageCheck.new(user_page_check_params)

    respond_to do |format|
      if @user_page_check.save
        format.html { redirect_to @user_page_check, notice: 'User page check was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_page_check }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_page_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_page_checks/1
  # PATCH/PUT /user_page_checks/1.json
  def update
    respond_to do |format|
      if @user_page_check.update(user_page_check_params)
        format.html { redirect_to @user_page_check, notice: 'User page check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_page_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_page_checks/1
  # DELETE /user_page_checks/1.json
  def destroy
    @user_page_check.destroy
    respond_to do |format|
      format.html { redirect_to user_page_checks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_page_check
      @user_page_check = UserPageCheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_page_check_params
      params.require(:user_page_check).permit(:user_id, :page_id)
    end
end

app/helpers/user_page_checks_helper.rb
module UserPageChecksHelper
end

app/views/user_page_checks/_form.html.erb
<%= simple_form_for(@user_page_check) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :user_id %>
    <%= f.input :page_id %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_page_checks/edit.html.erb
<h1>Editing user_page_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_page_check %> |
<%= link_to 'Back', user_page_checks_path %>

app/views/user_page_checks/index.html.erb
<h1>Listing user_page_checks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Page</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_page_checks.each do |user_page_check| %>
      <tr>
        <td><%= user_page_check.user_id %></td>
        <td><%= user_page_check.page_id %></td>
        <td><%= link_to 'Show', user_page_check %></td>
        <td><%= link_to 'Edit', edit_user_page_check_path(user_page_check) %></td>
        <td><%= link_to 'Destroy', user_page_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User page check', new_user_page_check_path %>

app/views/user_page_checks/new.html.erb
<h1>New user_page_check</h1>

<%= render 'form' %>

<%= link_to 'Back', user_page_checks_path %>

app/views/user_page_checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_page_check.user_id %>
</p>

<p>
  <strong>Page:</strong>
  <%= @user_page_check.page_id %>
</p>

<%= link_to 'Edit', edit_user_page_check_path(@user_page_check) %> |
<%= link_to 'Back', user_page_checks_path %>