config/routes.rb
CmsTerms::Application.routes.draw do

  resources :user_page_checks do
      member do
        delete 'check'
      end
  end

  resources :notes
  devise_for :users
  resources :pages do
      member do
        get 'view'
      end
  end

  

  root :to => "homes#index"
end

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.text_field :title %>
    <%= f.input :content %>
    <%= f.input :status %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.status %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'View', view_page_path(page) %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<% content_for :title do %>
<%= @page.title %>
<% end %>

<h1><%= @page.title %></h1>

<p><%= @page.content %></p>

app/views/pages/view.html.erb
<% content_for :title do %>
<%= @page.title %>
<% end %>

<h1><%= @page.title %></h1>

<p><%= @page.content %></p>